-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 18, 2019 at 05:06 PM
-- Server version: 10.3.15-MariaDB
-- PHP Version: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `survey`
--

-- --------------------------------------------------------

--
-- Table structure for table `puzzles`
--

CREATE TABLE `puzzles` (
  `id` int(11) NOT NULL,
  `titleId` varchar(255) DEFAULT NULL,
  `question` varchar(255) DEFAULT NULL,
  `options` varchar(255) DEFAULT NULL,
  `right_answer` varchar(255) DEFAULT NULL,
  `is_deleted` varchar(255) DEFAULT NULL,
  `created_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `puzzles`
--

INSERT INTO `puzzles` (`id`, `titleId`, `question`, `options`, `right_answer`, `is_deleted`, `created_at`, `updated_at`) VALUES
(8, '10', 'question2', NULL, '5', '0', NULL, NULL),
(9, '11', 'question2', NULL, '3', '0', NULL, NULL),
(10, '12', 'question2', 'tshs\r\nmxsn', '3', '0', NULL, '2019-09-18 16:42:48'),
(11, '12', 'question3', 'tshs\r\nmxsn', 'wdw', '0', NULL, '2019-09-18 16:42:48'),
(12, '13', 'cvd', 'tshs\r\nmxsn', 'sqsq', '0', NULL, '2019-09-12 23:44:30'),
(13, '14', 'question2', 'dd', 'wdw', '0', NULL, '2019-09-13 22:56:30'),
(14, '15', 'question2', 'dd', 'wdw', '0', NULL, '2019-09-13 22:56:42');

-- --------------------------------------------------------

--
-- Table structure for table `quiz_titles`
--

CREATE TABLE `quiz_titles` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `time` varchar(255) DEFAULT NULL,
  `is_deleted` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `quiz_titles`
--

INSERT INTO `quiz_titles` (`id`, `title`, `description`, `time`, `is_deleted`, `created_at`, `updated_at`) VALUES
(10, 'test45', NULL, NULL, '1', '2019-09-09 10:40:06', '2019-09-18 16:38:40'),
(11, 'Rajasthan', NULL, NULL, '1', '2019-09-12 16:23:34', '2019-09-18 16:38:44'),
(12, 'Rajasthan', 'jacbjjnjsmnxsnxjnsjx sm kjnjn', '67', '0', '2019-09-12 18:06:02', '2019-09-18 16:42:48'),
(13, 'Rajasthanuuu', 'snx s x s', '15', '0', '2019-09-12 18:14:30', '2019-09-13 17:22:45'),
(14, 'Rajasthan', 'snx s x s', '10:12PM', '0', '2019-09-13 17:26:30', '2019-09-13 22:56:30'),
(15, 'Rajasthan', 'snx s x s', '10:12PM', '0', '2019-09-13 17:26:42', '2019-09-13 22:56:42');

-- --------------------------------------------------------

--
-- Table structure for table `survey_basics`
--

CREATE TABLE `survey_basics` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `custom_css` text DEFAULT NULL,
  `is_deleted` int(11) NOT NULL,
  `created_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `survey_basics`
--

INSERT INTO `survey_basics` (`id`, `title`, `description`, `custom_css`, `is_deleted`, `created_at`, `updated_at`) VALUES
(1, 'First form', 'Description form updated', 'test css', 0, '2019-08-24 12:10:46', '2019-10-03 17:11:25'),
(3, 'survey form for farming technology.', 'sourceref is for sending additional source information. i.e. if quote was generated by a google search the source should be set to “google” the sourceref should contain additional information such as campaign link name “hol_im” which refers to the search term used.', '.heading_font h1{color:pink;}\r\n.card-header {background-color:lightpink;}', 0, '2019-10-08 16:59:20', '2019-10-08 17:51:29'),
(4, 'test45', 'j', 'sdxdx', 0, '2019-11-18 15:24:41', '2019-11-18 20:54:41');

-- --------------------------------------------------------

--
-- Table structure for table `survey_questions`
--

CREATE TABLE `survey_questions` (
  `id` int(11) NOT NULL,
  `question` varchar(255) DEFAULT NULL,
  `question_type` varchar(255) DEFAULT NULL,
  `options` varchar(255) DEFAULT NULL,
  `created_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) NOT NULL DEFAULT current_timestamp(),
  `survey_id` int(11) NOT NULL,
  `is_deleted` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `survey_questions`
--

INSERT INTO `survey_questions` (`id`, `question`, `question_type`, `options`, `created_at`, `updated_at`, `survey_id`, `is_deleted`) VALUES
(14, 'question3', 'radio', 'option 1, option 2', NULL, '2019-10-03 22:42:35', 1, 0),
(15, 'third question', 'dropdown', 'drop1,drop2,drop3', NULL, '2019-10-03 22:42:36', 1, 0),
(16, 'question2', 'text', 'input', NULL, '2019-10-03 22:42:36', 1, 0),
(17, 'checkbox type question', 'checkbox', 'check1, check2,chek3', NULL, '2019-10-03 22:42:36', 1, 0),
(30, 'For detailed information refer to the Campaigns section below.?', 'radio', 'The campaign , attribute of the quote ,not included the options ,elements are required.', NULL, '2019-10-08 23:19:43', 3, 0),
(31, '•	The quote MUST contain a policy holder. Partner and Dependents are optional.?', 'radio', 'There can be only ,one Policy holder and Partner ,there are a maximum', NULL, '2019-10-08 23:19:43', 3, 0),
(32, '•	The cover start date cannot be more than 60 days in the future and cannot be backdated more than 7 days?', 'dropdown', '•	The policy holder age , must be between 18 and 105,•	The partner age must ,be between 16 and 105.', NULL, '2019-10-08 23:19:43', 3, 0),
(33, 'question2', 'text', 'option 1, option 2', '2019-11-18 15:24:57', '2019-11-18 20:54:57', 4, 0),
(34, NULL, 'text', NULL, '2019-11-18 15:24:57', '2019-11-18 20:54:57', 4, 0);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'jal singh', 'jlsingh38@gmail.com', NULL, '$2y$10$8WqCoBEGSRtnAYGu2W91wOljQtnI2Kx2zHOAWMKu3t1I9OK7E5mce', 'ZSkUKGybGTMA8zOxzycqYl4k3MK0qUN9aS5IYoXQYYfHb2NHlsYmTpxY5yYF', '2019-06-28 04:04:14', '2019-06-28 04:04:14'),
(2, 'ravi', 'jlsingh382@gmail.com', NULL, '$2y$10$OoL6Qp8p6SNzofymJN3tAuqNDw4EexV6lAQe55PYmYOD.EZ0CbLWm', NULL, '2019-08-17 20:21:46', '2019-08-17 20:21:46');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `puzzles`
--
ALTER TABLE `puzzles`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `quiz_titles`
--
ALTER TABLE `quiz_titles`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `survey_basics`
--
ALTER TABLE `survey_basics`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `survey_questions`
--
ALTER TABLE `survey_questions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `puzzles`
--
ALTER TABLE `puzzles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- AUTO_INCREMENT for table `quiz_titles`
--
ALTER TABLE `quiz_titles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT for table `survey_basics`
--
ALTER TABLE `survey_basics`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `survey_questions`
--
ALTER TABLE `survey_questions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
